# Matrix Multiplication using NumPy

## Objective

Learn how matrix multiplication works mathematically and how it is implemented using NumPy.

---

### Topics Covered

- Creating matrices
- Matrix shapes
- Matrix multiplication
- Identity matrix
- Transpose
- Applications in Machine Learning

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]


In [ ]:
#Matrix Shape
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (2, 2)
Shape of B: (2, 2)


In [ ]:
#Matrix Multiplication
C = np.matmul(A, B)
print(C)

[[19 22]
 [43 50]]


In [5]:
C = A @ B

print(C)

[[19 22]
 [43 50]]


### Why two methods?

`np.matmul()` and `@` perform exactly the same matrix multiplication.

The `@` operator is simply cleaner to read.

In [ ]:
#Identity Matrix
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Zero Matrix
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Transpose
print(A.T)

[[1 3]
 [2 4]]


# Matrix Multiplication in Neural Networks

A neural network computes

Z = XW + b

where

- X = Input Matrix
- W = Weight Matrix
- b = Bias

Without matrix multiplication, neural networks cannot perform forward propagation.